### ISSUE TITLE
More imputation options

### ISSUE THREAD

**Issue by shaycrk** [dssg/collate#102]
In the future, we'll likely want to add additional imputation options (e.g., within-group mean, most frequent category for categoricals, most frequent pattern for categoricals, multiple imputation, etc.), but this will take a bit of extra work beyond the current imputation code. 

The current version simply provides a `COALESCE` snippet to drop in for a column definition, while these additional options will generally require additional joins, handling the categoricals as a group, or even pulling the data out of postgres for model-based imputations.

**Comment by jesteria** [comment]
This issue was moved to dssg/triage#309
