### ISSUE TITLE
add parameter to "Dummify" feature to use top n values by rank or frequency

### ISSUE THREAD

**Issue by rayidghani** [dssg/collate#34]
When creating dummy variables (or counts), allow option to say "Create dummy variables or counts for the top n most frequent values from a given field" instead of requiring user to pass values for the  top n individually. We can have the default behavior of creating an "other" field/feature

**Comment by mbauman** [comment]
Do we really want to make it easier to add a data-dependency in the feature choices?  I suppose this is something we implicitly do, but it feels wrong to me.

**Comment by mbauman** [comment]
With #38 this becomes much easier.  That said, I'we could still implement something like `collate.generate_top_n_categories('table', 'column', 10, engine)` — which would print out Python code for the top 10 categories in that column that you can just copypaste into a features file.

**Comment by mbauman** [comment]
I hereby retract my hesitation about implementing this feature. I think @jzanzig's [analysis here](https://github.com/dssg/triage/issues/33#issuecomment-284454535) is correct. It still introduces a funny data flow -- the `Aggregate` won't know what columns it generates until it touches the DB. So we'll need to think through how we get the DB connection to the aggregate, but that's not a show stopper.

**Comment by jesteria** [comment]
This issue was moved to dssg/triage#302
