### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by nanounanue** [dssg/collate#89]
In the `README` file, Does the  example:

```
fail = Aggregate({"fail_count": "(results = Fail)::int"}, "sum")
st = SpacetimeAggregation([fail], 'food_inspections',
                           group_intervals={"license_no":["2 year", "3 year"], "zip": ["1 year"]},
                           dates=["2016-01-01", "2015-01-01"],
                           date_column="inspection_date")
```

6 aggregations?  It is aggregating by:

- `license_no`, and the last 2 years, using the two `dates` field available
- `license_no` and the last 3 years, using the two `dates` field available
- `zip` and the last year, using the two `dates` fields available

?

**Comment by thcrock** [comment]
I believe this is out of date; there are separate `groups` and `intervals` keyword arguments. @mbauman @potash what should this section look like now?
