### ISSUE TITLE
Merge police branch of collate with sub_query_aggregation into master

### ISSUE THREAD

**Issue by harnav** [dssg/collate#96]
Currently there are three branches that claim to do this:
`ka/parallel`
`ka/sub_query`
`ka/parallel_pickle_error`
Running the pipeline using `ka/parallel` results in a pickle error. 
While the changes in `ka/parallel_pickle_error` are made on version 0.2.0 of collate which does not work with the police pipeline code.

**Comment by harnav** [comment]
Works if you use `Python 3.5` in conjunction with `ka/parallel`

**Comment by jesteria** [comment]
This issue was moved to dssg/triage#307
